### ISSUE TITLE
Usecase2 documentation

### ISSUE THREAD

**Issue by doriguzzi** [fp7-netide/Usecases#2]
Hi,

thanks for updating the README. However I see two things that could be improved:
- the mininet script should not include a path that usually does not exists in all computers (sudo ~/pyretic/mininet/mn -c). I solved by simply running "sudo python Topology/UC2_IITSystem.py", which should work on any computer.
- The IITS_NetManager.py application was not working for me with Ryu 3.27. I solved by updating to the latest version, namely v4.4. Maybe it should be mentioned in the README

--roberto

**Comment by ElisaRojas** [comment]
Thank you @doriguzzi !

@Juanma-Sanchez , I think you can just change the Mininet script with `sudo mn -c` instead of `sudo ~/pyretic/mininet/mn -c`. As for the Ryu version, what version are you currently running? Please indicate it in the README as Roberto suggests and also in #3 , as that might solve the problem @doriguzzi has.

**Comment by Juanma-Sanchez** [comment]
Hello,

Thanks @doriguzzi  for the advice on the mininet script, the ryu one is also updated now.

I initially used Ryu 3.23, after testing it in a new virtual machine with v3.27 I found that the code didn't distinguish between IPv6 and IPv4 (because of the configuration of mininet, there were no IPv6 packets in the other VM) packets and it crashed. With the new code I just uploaded it should work and I didn't get the error in #3 .
Trying to replicate the error, I have installed ryu 4.4 just to see the application doesn't work properly with this version. I'll try to figure out why and solve it asap.
